# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 522e95d4ca6e281a4da72b4aa32970f058d1583c26f4fa1e2b9f502f19d3d1a5267ac51198ec7d0892fbf7f70c6bda4eba19cb154c851366beea561aa37b098d

test:
  secret_key_base: 879549c95305c806cd4b005625915a8660972e8a159e31ce191c059c0ec19740afb8c85a7a57a94cd941361824fdc9bd136531569465843cf6df964f37556168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
